### ISSUE TITLE
Tokenization issue

### ISSUE THREAD

**Issue by polm** [UniversalDependencies/UD_Japanese-GSD#19]
Sentence train-s5734 has very strange tokenization. 

> アンケート用紙の余白に“8.2514:30”と書き入れる海老澤代表。

The number is tokenized like `8|.|25|1|4|:|30`. I assume this is an error, maybe a space was lost somewhere?

**Comment by polm** [comment]
In sentence train-s4488 there's a wrong tokenization.

> シートン・ホール大学でプレイしたデュークスは最終学年の1952-53シーズンには平均26.2得点22.2リバウンドを記録し、通算734リバウンドはNCAAデビジョン1の新記録と>なった。 

`NCAAデビジョン1` is tokenized as `NCAA|デ|ビジョン|1`.

**Comment by kanayamah** [comment]
@polm thank you for reports!  They will be fixed in v2.8.
