### ISSUE TITLE
repeated sentences in `ja_gsd-ud-test.conllu`

### ISSUE THREAD

**Issue by shijieyao** [UniversalDependencies/UD_Japanese-GSD#4]
Hi, not sure whether repeated sentences in the test set is trivial or not, but for future reference, I'd like to point out them as I've encountered while using the test set.

test-s205 & test-s208
test-s206 & test-s209
test-s207 & test-s210
test-s224 & test-s225
test-s247 & test-s248
test-s281 & test-s283

**Comment by kanayamah** [comment]
@shijieyeo, thank you very much.   We removed many duplicated sentences before the release of v2.0 but some of them still remain as you pointed out.  We will fix this in the next release.

**Comment by kanayamah** [comment]
other than 6 duplicated pairs in test, I found

- 23 pairs in train
- 5 pairs in dev/train
- 5 pairs in test/train

They will be removed from the train portion.

**Comment by kanayamah** [comment]
fixed in the v2.3 candidate.
